fs = require 'fs'
path = require 'path'
yaml = require 'js-yaml'
crypto = require 'crypto'
child = require 'child_process'
os = require 'os'

safeRun = (cmd) ->
  try
    res = child.spawnSync cmd,
      shell: true
      encoding: 'utf8'
    [res.status ? 1, res.stdout ? '', res.stderr ? '']
  catch e
    [1, '', String(e)]

@step =
  desc: "Capture environment info and create manifest"

  action: (S) ->
    outputDir = S.param 'output_dir'
    seed = S.param 'seed', null

    [freezeStatus, freezeStdout, freezeStderr] = safeRun 'python3 -m pip freeze'
    lockHash = null
    if freezeStatus is 0
      freezeText = String(freezeStdout).trimEnd() + "\n"
      lockHash = crypto.createHash('sha256').update(freezeText).digest('hex')
      S.saveThis path.join(outputDir, 'requirements.lock'), freezeText
    else
      console.warn "[manifest] pip freeze failed: #{String(freezeStderr).trim()}"

    manifest =
      timestamp_utc: new Date().toISOString().replace(/\.\d+Z$/, 'Z')
      seed: seed
      platform:
        system: os.platform()
        release: os.release()
        version: (os.version?() or 'unknown')
        machine: os.arch()
        processor: os.cpus()[0]?.model or 'unknown'
      executables:
        node: process.execPath
        python: 'python3'
      artifacts:
        requirements_lock: path.join(outputDir, 'requirements.lock')
        requirements_lock_sha256: lockHash
      notes: [
        'Generated by full/manifest.coffee'
        'This manifest anchors the environment for the run.'
      ]

    S.make 'run_manifest', manifest
    S.saveThis path.join(outputDir, 'run_manifest.json'), manifest
    S.done()
    return
