@step =
  desc: "Generate prompt-formatting policy JSON"

  action: (S) ->
    contract = await S.need 'data_contract'
    trainRows = await S.need 'train_rows'

    templateName = S.param 'template_name'
    stopStrings = S.param 'stop_strings'
    useEosToken = S.param 'use_eos_token'

    textField = 'text'
    if contract?.schema?.fields?
      for k, v of contract.schema.fields
        if String(v).toLowerCase() is 'string'
          textField = k
          break

    fmtPlain = (text) -> text
    fmtIclMinimal = (text) ->
      "### Instruction\nShare an important thought.\n\n### Response\n#{String(text).trim()}"
    fmtLlama3Style = (text) ->
      "<s>[INSTRUCTION]\nShare an important thought.\n[/INSTRUCTION]\n[RESPONSE]\n#{String(text).trim()}\n[/RESPONSE]</s>"

    formatters =
      plain_text_passthrough: fmtPlain
      icl_minimal: fmtIclMinimal
      llama3_style: fmtLlama3Style

    formatter = formatters[templateName]
    throw new Error "Unknown formatter template_name: #{templateName}" unless formatter?

    samples = []
    for row in trainRows ? [] when samples.length < 3
      samples.push row[textField] if typeof row?[textField] is 'string'

    policy =
      template_name: templateName
      text_field: textField
      stop_strings: stopStrings
      use_eos_token: useEosToken
      preview: samples.slice(0, 2).map (sample) ->
        before: sample
        after: formatter sample
      notes: [
        'Generated by full/prepare_prompts.coffee'
        'Describes how prompts should be formatted during fine-tuning.'
      ]

    S.make 'prompt_policy', policy
    S.saveThis 'prepare_prompts:policy', policy
    S.done()
    return
