// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var compactText, preserveHumanRevision;

  compactText = function(value) {
    return String(value != null ? value : '').replace(/\s+/g, ' ').trim();
  };

  preserveHumanRevision = function(draft, existingDraft, currentSourceHash) {
    var merged, ref, ref1;
    if ((existingDraft != null ? existingDraft.revised_by_human : void 0) !== true) {
      return draft;
    }
    if (String((ref = existingDraft != null ? existingDraft.campaign_source_hash : void 0) != null ? ref : '') !== String(currentSourceHash != null ? currentSourceHash : '')) {
      return draft;
    }
    merged = Object.assign({}, draft);
    if (typeof existingDraft.subject === 'string') {
      merged.subject = existingDraft.subject;
    }
    if (typeof existingDraft.email_body === 'string') {
      merged.email_body = existingDraft.email_body;
    }
    merged.revised_by_human = true;
    merged.revised_at = (ref1 = existingDraft.revised_at) != null ? ref1 : new Date().toISOString();
    return merged;
  };

  this.step = {
    desc: 'Build reviewed outreach drafts from source material and audiences.',
    action: async function(L, stepName, M) {
      var audienceProfiles, audienceProfilesKey, baseHighlights, callToAction, contactLedger, contactLedgerKey, draft, drafts, existingByDraftId, existingDoc, existingDrafts, experiment, i, len, messageDraftsTarget, payload, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, signatureName, sourceMaterial, sourceMaterialKey;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      sourceMaterialKey = 'source_material';
      audienceProfilesKey = 'audience_profiles';
      contactLedgerKey = 'contact_ledger';
      sourceMaterial = (await L.need(sourceMaterialKey));
      audienceProfiles = (await L.need(audienceProfilesKey));
      contactLedger = (await L.need(contactLedgerKey));
      if (sourceMaterial == null) {
        throw new Error(`[${stepName}] Missing required artifact '${sourceMaterialKey}'`);
      }
      if ((audienceProfiles != null ? audienceProfiles.profiles : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${audienceProfilesKey}'`);
      }
      if ((contactLedger != null ? contactLedger.entries : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${contactLedgerKey}'`);
      }
      callToAction = (ref1 = M.getStepParam(stepName, 'call_to_action')) != null ? ref1 : 'Request review before any outreach is sent.';
      signatureName = (ref2 = (ref3 = (ref4 = M.getStepParam(stepName, 'signature_name')) != null ? ref4 : sourceMaterial.brand_name) != null ? ref3 : (ref5 = experiment.run) != null ? ref5.brand_name : void 0) != null ? ref2 : 'Team';
      messageDraftsTarget = (ref6 = experiment.artifacts) != null ? (ref7 = ref6.message_drafts) != null ? ref7.target : void 0 : void 0;
      existingDoc = messageDraftsTarget != null ? (ref8 = M.theLowdown(messageDraftsTarget)) != null ? ref8.value : void 0 : null;
      existingDrafts = Array.isArray(existingDoc != null ? existingDoc.drafts : void 0) ? existingDoc.drafts : [];
      existingByDraftId = {};
      for (i = 0, len = existingDrafts.length; i < len; i++) {
        draft = existingDrafts[i];
        if ((draft != null ? draft.draft_id : void 0) != null) {
          existingByDraftId[draft.draft_id] = draft;
        }
      }
      baseHighlights = ((ref9 = sourceMaterial.highlights) != null ? ref9 : []).slice(0, 2).join(' ');
      drafts = audienceProfiles.profiles.map(function(profile) {
        var draftId, emailBody, followUp, hook, ledgerEntry, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, subject;
        ledgerEntry = contactLedger.entries.find(function(entry) {
          return entry.audience === profile.audience_label;
        });
        hook = compactText(profile.angle);
        draftId = `draft_${profile.audience_key}`;
        subject = `${sourceMaterial.brand_name}: ${profile.audience_label} draft`;
        emailBody = [`Hi ${(ref10 = ledgerEntry != null ? ledgerEntry.contact_name : void 0) != null ? ref10 : profile.audience_label},`, "", `I’m sharing a draft outreach note for review regarding ${sourceMaterial.campaign_name} in ${(ref11 = sourceMaterial.launch_city) != null ? ref11 : 'the local market'}.`, `${hook}`, "", `${baseHighlights}`, "", `${callToAction}`, "", "Best,", signatureName].join("\n");
        followUp = `Follow up with ${String((ref12 = profile.audience_label) != null ? ref12 : '').toLowerCase()} only after human review and explicit approval.`;
        draft = {
          audience_key: profile.audience_key,
          draft_id: draftId,
          campaign_source_hash: (ref13 = sourceMaterial.source_hash) != null ? ref13 : null,
          audience_label: profile.audience_label,
          organization: (ref14 = ledgerEntry != null ? ledgerEntry.organization : void 0) != null ? ref14 : null,
          contact_name: (ref15 = ledgerEntry != null ? ledgerEntry.contact_name : void 0) != null ? ref15 : null,
          contact_role: (ref16 = ledgerEntry != null ? ledgerEntry.contact_role : void 0) != null ? ref16 : null,
          contact_channel: (ref17 = ledgerEntry != null ? ledgerEntry.contact_channel : void 0) != null ? ref17 : null,
          subject: subject,
          pitch_summary: hook,
          email_body: emailBody,
          follow_up_note: followUp,
          review_required: true
        };
        return preserveHumanRevision(draft, existingByDraftId[draftId], sourceMaterial.source_hash);
      });
      payload = {
        generated_for: sourceMaterial.campaign_name,
        campaign_source_hash: (ref10 = sourceMaterial.source_hash) != null ? ref10 : null,
        draft_count: drafts.length,
        drafts: drafts,
        constraints: {
          live_send_enabled: false,
          network_posting_enabled: false,
          requires_human_review: true
        }
      };
      L.make('message_drafts', payload);
      L.done();
    }
  };

}).call(this);
