// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var compactText, decisionBucket, isBlank, makeFact, makeImprovement, makeTalkingPoint, uniqueStrings;

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  compactText = function(value) {
    return String(value != null ? value : '').replace(/\s+/g, ' ').trim();
  };

  decisionBucket = function(decision) {
    var ref, value;
    value = String((ref = decision != null ? decision.decision : void 0) != null ? ref : '').trim().toLowerCase();
    if ((decision != null ? decision.approved_for_send : void 0) === true || (value === 'approved' || value === 'approve')) {
      return 'approved';
    }
    if (value === 'rejected' || value === 'reject') {
      return 'rejected';
    }
    if (value === 'revise') {
      return 'revise';
    }
    return 'pending_review';
  };

  makeFact = function(result) {
    var excerpt, prefix, ref;
    excerpt = compactText((ref = result != null ? result.short_text_excerpt : void 0) != null ? ref : '');
    if (!excerpt.length) {
      return null;
    }
    prefix = !isBlank(result != null ? result.title : void 0) ? `${result.title}: ` : '';
    return `${prefix}${excerpt}`.slice(0, 320);
  };

  makeImprovement = function(draft, result) {
    var org, ref, ref1, ref2, ref3, title;
    title = compactText((ref = result != null ? result.title : void 0) != null ? ref : '');
    org = (ref1 = (ref2 = (ref3 = draft != null ? draft.organization : void 0) != null ? ref3 : result != null ? result.organization : void 0) != null ? ref2 : draft != null ? draft.audience_label : void 0) != null ? ref1 : 'the target';
    if (title.length) {
      return `Reference ${org}'s current focus using '${title}' to make the outreach feel specific.`;
    } else {
      return `Use the fetched context to make the note to ${org} more specific and timely.`;
    }
  };

  makeTalkingPoint = function(draft, result) {
    var excerpt, org, ref, ref1, ref2, ref3, ref4, ref5, sentence;
    excerpt = compactText((ref = result != null ? result.short_text_excerpt : void 0) != null ? ref : '');
    org = (ref1 = (ref2 = (ref3 = draft != null ? draft.organization : void 0) != null ? ref3 : result != null ? result.organization : void 0) != null ? ref2 : draft != null ? draft.audience_label : void 0) != null ? ref1 : 'the audience';
    if (!excerpt.length) {
      return null;
    }
    sentence = (ref4 = excerpt.split(/(?<=[.!?])\s+/)[0]) != null ? ref4 : excerpt;
    return `Tie ${(ref5 = draft != null ? draft.brand_name : void 0) != null ? ref5 : 'the campaign'} to ${org} context: ${sentence}`.slice(0, 280);
  };

  uniqueStrings = function(values) {
    var i, len, rows, seen, text, value;
    seen = new Set();
    rows = [];
    for (i = 0, len = values.length; i < len; i++) {
      value = values[i];
      if (!(!isBlank(value))) {
        continue;
      }
      text = String(value).trim();
      if (seen.has(text)) {
        continue;
      }
      seen.add(text);
      rows.push(text);
    }
    return rows;
  };

  this.step = {
    desc: 'Generate research-based draft improvement suggestions without overwriting human text.',
    action: async function(L, stepName, M) {
      var decision, decisionsByDraftId, draft, draftId, enrichedDrafts, experiment, i, j, k, len, len1, len2, matchesAudience, matchesContact, matchesOrganization, messageDrafts, messageDraftsKey, payload, ref, ref1, ref2, ref3, ref4, ref5, requestId, researchResults, researchResultsKey, result, resultsByDraftId, reviewDecisions, reviewDecisionsKey;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      researchResultsKey = 'research_results';
      messageDraftsKey = 'message_drafts';
      reviewDecisionsKey = 'review_decisions';
      researchResults = (await L.need(researchResultsKey));
      messageDrafts = (await L.need(messageDraftsKey));
      reviewDecisions = (await L.need(reviewDecisionsKey));
      if (!Array.isArray(researchResults != null ? researchResults.results : void 0)) {
        throw new Error(`[${stepName}] Missing required artifact '${researchResultsKey}'`);
      }
      if (!Array.isArray(messageDrafts != null ? messageDrafts.drafts : void 0)) {
        throw new Error(`[${stepName}] Missing required artifact '${messageDraftsKey}'`);
      }
      if (!Array.isArray(reviewDecisions != null ? reviewDecisions.decisions : void 0)) {
        throw new Error(`[${stepName}] Missing required artifact '${reviewDecisionsKey}'`);
      }
      decisionsByDraftId = {};
      ref1 = reviewDecisions.decisions;
      for (i = 0, len = ref1.length; i < len; i++) {
        decision = ref1[i];
        if ((decision != null ? decision.draft_id : void 0) != null) {
          decisionsByDraftId[decision.draft_id] = decision;
        }
      }
      resultsByDraftId = {};
      ref2 = researchResults.results;
      for (j = 0, len1 = ref2.length; j < len1; j++) {
        result = ref2[j];
        if (!(result != null)) {
          continue;
        }
        draftId = null;
        requestId = String((ref3 = result != null ? result.request_id : void 0) != null ? ref3 : '').trim();
        if (/^research_(review|follow_up)_/i.test(requestId)) {
          draftId = requestId.replace(/^research_(review|follow_up)_/i, '');
        }
        if (draftId == null) {
          ref4 = messageDrafts.drafts;
          for (k = 0, len2 = ref4.length; k < len2; k++) {
            draft = ref4[k];
            if (!((draft != null ? draft.draft_id : void 0) != null)) {
              continue;
            }
            matchesOrganization = compactText(result.organization) === compactText(draft.organization);
            matchesContact = compactText(result.contact_name) === compactText(draft.contact_name);
            matchesAudience = compactText(result.audience) === compactText(draft.audience_label);
            if ((matchesOrganization && matchesContact) || (matchesAudience && !isBlank(result.audience))) {
              draftId = draft.draft_id;
              break;
            }
          }
        }
        if (draftId == null) {
          continue;
        }
        if (resultsByDraftId[draftId] == null) {
          resultsByDraftId[draftId] = [];
        }
        resultsByDraftId[draftId].push(result);
      }
      enrichedDrafts = messageDrafts.drafts.map(function(draft) {
        var matchedResults, ref10, ref5, ref6, ref7, ref8, ref9, relevantFacts, suggestedImprovements, talkingPoints;
        draftId = (ref5 = draft != null ? draft.draft_id : void 0) != null ? ref5 : '';
        decision = (ref6 = decisionsByDraftId[draftId]) != null ? ref6 : null;
        matchedResults = (ref7 = resultsByDraftId[draftId]) != null ? ref7 : [];
        relevantFacts = uniqueStrings(matchedResults.map(function(result) {
          return makeFact(result);
        }));
        suggestedImprovements = uniqueStrings(matchedResults.map(function(result) {
          return makeImprovement(draft, result);
        }));
        talkingPoints = uniqueStrings(matchedResults.map(function(result) {
          return makeTalkingPoint(draft, result);
        }));
        return {
          draft_id: draftId,
          audience_label: (ref8 = draft != null ? draft.audience_label : void 0) != null ? ref8 : '',
          organization: (ref9 = draft != null ? draft.organization : void 0) != null ? ref9 : '',
          contact_name: (ref10 = draft != null ? draft.contact_name : void 0) != null ? ref10 : '',
          decision: decisionBucket(decision),
          approved_for_send: (decision != null ? decision.approved_for_send : void 0) === true,
          research_enriched: true,
          matched_request_ids: uniqueStrings(matchedResults.map(function(result) {
            return result != null ? result.request_id : void 0;
          })),
          matched_result_count: matchedResults.length,
          suggested_improvements: suggestedImprovements,
          additional_talking_points: talkingPoints,
          relevant_facts: relevantFacts
        };
      });
      payload = {
        generated_for: (ref5 = experiment.run) != null ? ref5.campaign_name : void 0,
        draft_count: messageDrafts.drafts.length,
        enriched_count: enrichedDrafts.filter(function(row) {
          return row.matched_result_count > 0;
        }).length,
        enriched_drafts: enrichedDrafts,
        summary: {
          fetched_result_count: researchResults.results.length,
          drafts_with_research: enrichedDrafts.filter(function(row) {
            return row.matched_result_count > 0;
          }).length,
          drafts_without_research: enrichedDrafts.filter(function(row) {
            return row.matched_result_count === 0;
          }).length,
          suggestions_only: true
        }
      };
      L.make('enriched_drafts', payload);
      L.done();
    }
  };

}).call(this);
