// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var SEARCH_ENGINE_HOSTS, axios, cheerio, extractTitleAndText, isApprovedResearchRequest, isBlank, normalizeAllowedTarget;

  axios = require('axios');

  cheerio = require('cheerio');

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  SEARCH_ENGINE_HOSTS = new Set(['google.com', 'www.google.com', 'bing.com', 'www.bing.com', 'search.yahoo.com', 'duckduckgo.com', 'www.duckduckgo.com', 'yandex.com', 'www.yandex.com']);

  normalizeAllowedTarget = function(raw, allowQueryString = false) {
    var host, parsed, ref, text;
    text = String(raw != null ? raw : '').trim();
    if (!text.length) {
      return null;
    }
    if (/[*?]/.test(text)) {
      return {
        error: 'wildcards_not_allowed'
      };
    }
    if (/^https?:\/\//i.test(text)) {
      try {
        parsed = new URL(text);
        if (!/^https?:$/i.test(parsed.protocol)) {
          return null;
        }
        host = parsed.hostname.toLowerCase();
        if (SEARCH_ENGINE_HOSTS.has(host)) {
          return {
            error: 'search_engine_domain_not_allowed'
          };
        }
        if (((ref = parsed.search) != null ? ref.length : void 0) && allowQueryString !== true) {
          return {
            error: 'query_string_not_allowed'
          };
        }
        return {
          source: text,
          host: host,
          url: parsed.toString(),
          isFullUrl: true
        };
      } catch (error) {
        return {
          error: 'invalid_url'
        };
      }
    }
    host = text.replace(/^https?:\/\//i, '').replace(/\/.*$/, '').trim().toLowerCase();
    if (!host.length) {
      return null;
    }
    if (SEARCH_ENGINE_HOSTS.has(host)) {
      return {
        error: 'search_engine_domain_not_allowed'
      };
    }
    return {
      source: text,
      host: host,
      url: `https://${host}/`,
      isFullUrl: false
    };
  };

  extractTitleAndText = function(html) {
    var $, text, title;
    $ = cheerio.load(String(html != null ? html : ''));
    title = $('title').first().text().replace(/\s+/g, ' ').trim();
    text = $('body').text().replace(/\s+/g, ' ').trim();
    return {
      title: title,
      short_text_excerpt: text.slice(0, 500)
    };
  };

  isApprovedResearchRequest = function(request) {
    var ref;
    return String((ref = request != null ? request.status : void 0) != null ? ref : '').trim().toLowerCase() === 'approved_for_research' && Array.isArray(request != null ? request.allowed_domains : void 0) && request.allowed_domains.length > 0;
  };

  this.step = {
    desc: 'Fetch allowlisted read-only research content for approved publicist requests.',
    action: async function(L, stepName, M) {
      var allowQueryString, contentType, err, experiment, extracted, finalHost, finalUrl, i, invalidReasons, j, k, len, len1, len2, maxResponseBytes, normalized, normalizedTargets, payload, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, request, requestId, researchRequests, researchRequestsKey, response, results, row, skipped, target, text, timeoutMs;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      researchRequestsKey = 'research_requests';
      researchRequests = (await L.need(researchRequestsKey));
      if (!Array.isArray(researchRequests != null ? researchRequests.research_requests : void 0)) {
        throw new Error(`[${stepName}] Missing required artifact '${researchRequestsKey}'`);
      }
      timeoutMs = Number((ref1 = M.getStepParam(stepName, 'timeout_ms')) != null ? ref1 : 5000);
      maxResponseBytes = Number((ref2 = M.getStepParam(stepName, 'max_response_bytes')) != null ? ref2 : 262144);
      results = [];
      skipped = [];
      ref3 = researchRequests.research_requests;
      for (i = 0, len = ref3.length; i < len; i++) {
        request = ref3[i];
        requestId = (ref4 = request != null ? request.request_id : void 0) != null ? ref4 : '';
        if (String((ref5 = request != null ? request.status : void 0) != null ? ref5 : '').trim().toLowerCase() !== 'approved_for_research') {
          skipped.push({
            request_id: requestId,
            reason: 'status_not_approved_for_research'
          });
          continue;
        }
        if (!(Array.isArray(request != null ? request.allowed_domains : void 0) && request.allowed_domains.length > 0)) {
          skipped.push({
            request_id: requestId,
            reason: 'allowed_domains_empty'
          });
          continue;
        }
        allowQueryString = (request != null ? request.allow_query_string : void 0) === true;
        normalizedTargets = [];
        invalidReasons = [];
        ref6 = request.allowed_domains;
        for (j = 0, len1 = ref6.length; j < len1; j++) {
          target = ref6[j];
          normalized = normalizeAllowedTarget(target, allowQueryString);
          if ((normalized != null ? normalized.error : void 0) != null) {
            invalidReasons.push(`${String(target != null ? target : '').trim()}:${normalized.error}`);
            continue;
          }
          if (normalized != null) {
            normalizedTargets.push(normalized);
          }
        }
        if (!normalizedTargets.length) {
          skipped.push({
            request_id: requestId,
            reason: 'allowed_domains_invalid',
            detail: invalidReasons
          });
          continue;
        }
        for (k = 0, len2 = normalizedTargets.length; k < len2; k++) {
          target = normalizedTargets[k];
          row = {
            request_id: requestId,
            audience: (ref7 = request.audience) != null ? ref7 : '',
            organization: (ref8 = request.organization) != null ? ref8 : '',
            contact_name: (ref9 = request.contact_name) != null ? ref9 : '',
            query_terms: (ref10 = request.suggested_search_terms) != null ? ref10 : [],
            url: target.url,
            status_code: null,
            title: '',
            short_text_excerpt: '',
            fetched_at: null,
            errors: []
          };
          try {
            response = (await axios.get(target.url, {
              timeout: timeoutMs,
              maxContentLength: maxResponseBytes,
              maxBodyLength: maxResponseBytes,
              responseType: 'text',
              maxRedirects: 5,
              validateStatus: function() {
                return true;
              },
              beforeRedirect: function(options, responseDetails) {
                var nextHost, ref11;
                nextHost = String((ref11 = options != null ? options.hostname : void 0) != null ? ref11 : '').toLowerCase();
                if (nextHost !== target.host) {
                  throw new Error("redirect_outside_allowed_hostname");
                }
              },
              headers: {
                'User-Agent': 'publicist-research-fetch/1.0',
                'Accept': 'text/html, text/plain;q=0.9, */*;q=0.1'
              }
            }));
            row.status_code = response.status;
            row.fetched_at = new Date().toISOString();
            finalUrl = String((ref11 = (ref12 = response.request) != null ? (ref13 = ref12.res) != null ? ref13.responseUrl : void 0 : void 0) != null ? ref11 : target.url);
            try {
              finalHost = new URL(finalUrl).hostname.toLowerCase();
              if (finalHost !== target.host) {
                row.errors.push('redirect_outside_allowed_hostname');
              }
            } catch (error) {
              row.errors.push('invalid_final_url');
            }
            contentType = String((ref14 = (ref15 = response.headers) != null ? ref15['content-type'] : void 0) != null ? ref14 : '');
            if (/^text\/html\b/i.test(contentType) || contentType.length === 0) {
              extracted = extractTitleAndText(response.data);
              row.title = extracted.title;
              row.short_text_excerpt = extracted.short_text_excerpt;
            } else if (/^text\//i.test(contentType)) {
              text = String((ref16 = response.data) != null ? ref16 : '').replace(/\s+/g, ' ').trim();
              row.short_text_excerpt = text.slice(0, 500);
            } else {
              row.errors.push(`unsupported_content_type: ${contentType}`);
            }
          } catch (error) {
            err = error;
            row.fetched_at = new Date().toISOString();
            row.errors.push(String((ref17 = err != null ? err.message : void 0) != null ? ref17 : err));
          }
          results.push(row);
        }
      }
      payload = {
        generated_for: (ref18 = experiment.run) != null ? ref18.campaign_name : void 0,
        fetch_mode: 'approved_allowlist_get_only',
        timeout_ms: timeoutMs,
        max_response_bytes: maxResponseBytes,
        results: results,
        skipped: skipped,
        summary: {
          approved_request_count: researchRequests.research_requests.filter(isApprovedResearchRequest).length,
          fetched_result_count: results.length,
          skipped_count: skipped.length
        }
      };
      L.make('research_results', payload);
      L.done();
    }
  };

}).call(this);
