// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var DEFAULT_CAMPAIGN_CONFIG_PATH, audienceMap, buildProfile, inferAudienceKeys, isBlank, readCampaignAudienceConfig;

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  DEFAULT_CAMPAIGN_CONFIG_PATH = 'source/publicist_campaign.yaml';

  audienceMap = {
    technical_press: {
      label: 'Technical press',
      angle: 'Explain the technical novelty and why the build system matters now.',
      rationale: 'Trade and engineering writers can translate the system for informed readers.'
    },
    industry_partners: {
      label: 'Industry partners',
      angle: 'Show where the campaign fits into real deployment, manufacturing, or integration work.',
      rationale: 'Potential partners need a concrete collaboration frame and mutual benefit.'
    },
    research_labs: {
      label: 'Research labs',
      angle: 'Emphasize experimental value, validation paths, and scientific relevance.',
      rationale: 'Labs and institutes respond to rigor, feasibility, and research utility.'
    },
    pilot_customers: {
      label: 'Pilot customers',
      angle: 'Focus on the practical use case, first deployment path, and near-term value.',
      rationale: 'Prospective adopters need a clear reason to trial the work.'
    },
    arts_press: {
      label: 'Arts press',
      angle: 'Frame the campaign as a distinct artistic launch with a clear voice and audience.',
      rationale: 'Arts writers look for a compelling creative point of view and cultural relevance.'
    },
    curators_programmers: {
      label: 'Curators and programmers',
      angle: 'Highlight why the work fits a program, season, or event context.',
      rationale: 'Programmers need curation-ready language and a concrete fit.'
    },
    venue_partners: {
      label: 'Venue partners',
      angle: 'Focus on live presentation, audience experience, and operational fit.',
      rationale: 'Venues need confidence that the work belongs in their room and calendar.'
    },
    creative_collaborators: {
      label: 'Creative collaborators',
      angle: 'Describe what kinds of artists, producers, or makers could build on the work.',
      rationale: 'Collaborators need to see the opening for joint creation.'
    },
    industry_press: {
      label: 'Industry press',
      angle: 'Present the campaign as a meaningful development in its field.',
      rationale: 'General trade coverage helps establish baseline visibility.'
    },
    strategic_partners: {
      label: 'Strategic partners',
      angle: 'Clarify the shared opportunity and why the campaign matters to both sides.',
      rationale: 'Partnership outreach needs a mutual-value frame.'
    },
    community_allies: {
      label: 'Community allies',
      angle: 'Connect the campaign to the community it serves or activates.',
      rationale: 'Community groups amplify work that aligns with their mission.'
    },
    direct_opportunities: {
      label: 'Direct opportunities',
      angle: 'Focus on immediate openings for placement, collaboration, or response.',
      rationale: 'This keeps the outreach practical when the category is still forming.'
    }
  };

  inferAudienceKeys = function(sourceMaterial) {
    var ref, text;
    text = String((ref = sourceMaterial != null ? sourceMaterial.source_text : void 0) != null ? ref : '').toLowerCase();
    if (/(orbit|orbital|space|robot|robots|structur|triangle|triangular|frame|frames|assembly)/.test(text)) {
      return ['technical_press', 'industry_partners', 'research_labs', 'pilot_customers'];
    }
    if (/(audio|visual|music|musician|studio|ensemble|composition|performance|live session|immersive|resonance)/.test(text)) {
      return ['arts_press', 'curators_programmers', 'venue_partners', 'creative_collaborators'];
    }
    return ['industry_press', 'strategic_partners', 'community_allies', 'direct_opportunities'];
  };

  readCampaignAudienceConfig = function(M) {
    var doc, ref;
    doc = (ref = M.theLowdown(DEFAULT_CAMPAIGN_CONFIG_PATH)) != null ? ref.value : void 0;
    if (!((doc != null) && typeof doc === 'object' && !Array.isArray(doc))) {
      return null;
    }
    return doc;
  };

  buildProfile = function(audienceKey, index, campaignName, proofPoints, overrideSpec = {}) {
    var recommendedChannel, ref, ref1, ref2, ref3, ref4, spec;
    spec = Object.assign({}, (ref = audienceMap[audienceKey]) != null ? ref : {}, overrideSpec != null ? overrideSpec : {});
    recommendedChannel = String((ref1 = spec.recommended_channel) != null ? ref1 : '').trim().length ? spec.recommended_channel : 'reviewed_email_draft';
    return {
      audience_index: index + 1,
      audience_key: audienceKey,
      audience_label: (ref2 = spec.label) != null ? ref2 : audienceKey,
      angle: (ref3 = spec.angle) != null ? ref3 : 'General awareness of the campaign.',
      rationale: (ref4 = spec.rationale) != null ? ref4 : 'Relevant audience for reviewed outreach drafts.',
      recommended_channel: recommendedChannel,
      campaign_name: campaignName,
      proof_points: proofPoints.slice(0, 2),
      review_required: true
    };
  };

  this.step = {
    desc: 'Identify audience profiles from workspace campaign configuration or inferred source context.',
    action: async function(L, stepName, M) {
      var artifactKey, audienceOverrides, campaignConfig, campaignName, configuredAudiences, experiment, payload, profiles, proofPoints, ref, ref1, ref2, ref3, ref4, ref5, selectedAudienceKeys, sourceMaterial;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      artifactKey = 'source_material';
      sourceMaterial = (await L.need(artifactKey));
      if (sourceMaterial == null) {
        throw new Error(`[${stepName}] Missing required artifact '${artifactKey}'`);
      }
      campaignConfig = readCampaignAudienceConfig(M);
      configuredAudiences = Array.isArray(campaignConfig != null ? campaignConfig.priority_audiences : void 0) ? campaignConfig.priority_audiences : null;
      audienceOverrides = ((campaignConfig != null ? campaignConfig.audience_overrides : void 0) != null) && typeof campaignConfig.audience_overrides === 'object' ? campaignConfig.audience_overrides : {};
      selectedAudienceKeys = (configuredAudiences != null ? configuredAudiences.length : void 0) ? configuredAudiences : inferAudienceKeys(sourceMaterial);
      if (!(Array.isArray(selectedAudienceKeys) && selectedAudienceKeys.length > 0)) {
        throw new Error(`[${stepName}] Could not determine any audiences`);
      }
      proofPoints = (ref1 = sourceMaterial.highlights) != null ? ref1 : [];
      campaignName = (ref2 = sourceMaterial.campaign_name) != null ? ref2 : (ref3 = experiment.run) != null ? ref3.campaign_name : void 0;
      profiles = selectedAudienceKeys.map(function(audienceKey, index) {
        return buildProfile(audienceKey, index, campaignName, proofPoints, audienceOverrides[audienceKey]);
      });
      payload = {
        generated_for: campaignName,
        campaign_source_hash: (ref4 = sourceMaterial.source_hash) != null ? ref4 : null,
        audience_count: profiles.length,
        profiles: profiles,
        notes: {
          source_material_key: 'source_material',
          campaign_config_path: DEFAULT_CAMPAIGN_CONFIG_PATH,
          used_campaign_config: Array.isArray(configuredAudiences) && configuredAudiences.length > 0,
          review_owner: (ref5 = experiment.run) != null ? ref5.review_owner : void 0,
          draft_only: true
        }
      };
      L.make('audience_profiles', payload);
      L.done();
    }
  };

}).call(this);
