// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var DatabaseSync, fs, path;

  fs = require('fs');

  path = require('path');

  ({DatabaseSync} = require('node:sqlite'));

  this.step = {
    desc: 'Initialize the dedicated publicist SQLite memory database.',
    action: function(L, stepName, M) {
      var db, dbExisted, execRoot, experiment, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, report, schemaPath, schemaText, sqlitePath;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      execRoot = (ref1 = (ref2 = M.theLowdown('env/EXEC')) != null ? ref2.value : void 0) != null ? ref1 : process.cwd();
      sqlitePath = path.resolve(String((ref3 = (ref4 = M.getStepParam(stepName, 'sqlite_db')) != null ? ref4 : (ref5 = experiment.run) != null ? ref5['runtime.sqlite'] : void 0) != null ? ref3 : 'runtime/publicist.sqlite'));
      schemaPath = path.resolve(execRoot, String((ref6 = M.getStepParam(stepName, 'schema_path')) != null ? ref6 : 'db/publicist/schema.sql'));
      if (!fs.existsSync(schemaPath)) {
        throw new Error(`[${stepName}] Missing schema file '${schemaPath}'`);
      }
      fs.mkdirSync(path.dirname(sqlitePath), {
        recursive: true
      });
      schemaText = fs.readFileSync(schemaPath, 'utf8');
      dbExisted = fs.existsSync(sqlitePath);
      db = new DatabaseSync(sqlitePath);
      try {
        db.exec(schemaText);
      } finally {
        db.close();
      }
      report = {
        generated_for: (ref7 = experiment.run) != null ? ref7.campaign_name : void 0,
        sqlite_path: sqlitePath,
        schema_path: schemaPath,
        db_existed_before: dbExisted,
        db_available: true,
        initialized_at: new Date().toISOString()
      };
      L.make('sqlite_init_report', report);
      L.done();
    }
  };

}).call(this);
