// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var freshDecision;

  freshDecision = function(draft, fallbackId) {
    var ref, ref1, ref2;
    return {
      draft_id: (ref = draft.draft_id) != null ? ref : fallbackId,
      contact_name: (ref1 = draft.contact_name) != null ? ref1 : '',
      organization: (ref2 = draft.organization) != null ? ref2 : '',
      decision: 'pending_review',
      reviewer_notes: "",
      approved_for_send: false,
      reviewed_at: null,
      updated_at: new Date().toISOString()
    };
  };

  this.step = {
    desc: 'Initialize draft-only human review decisions for outreach drafts.',
    action: async function(L, stepName, M) {
      var currentSourceHash, decisions, entry, existingByDraftId, existingDecisions, existingDoc, experiment, i, j, len, len1, messageDrafts, messageDraftsKey, payload, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, reviewDecisionsTarget;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      messageDraftsKey = 'message_drafts';
      messageDrafts = (await L.need(messageDraftsKey));
      if ((messageDrafts != null ? messageDrafts.drafts : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${messageDraftsKey}'`);
      }
      currentSourceHash = String((ref1 = messageDrafts != null ? messageDrafts.campaign_source_hash : void 0) != null ? ref1 : '');
      reviewDecisionsTarget = (ref2 = experiment.artifacts) != null ? (ref3 = ref2.review_decisions) != null ? ref3.target : void 0 : void 0;
      existingDoc = reviewDecisionsTarget != null ? (ref4 = M.theLowdown(reviewDecisionsTarget)) != null ? ref4.value : void 0 : null;
      existingDecisions = Array.isArray(existingDoc != null ? existingDoc.decisions : void 0) ? existingDoc.decisions : [];
      existingByDraftId = {};
      for (i = 0, len = existingDecisions.length; i < len; i++) {
        entry = existingDecisions[i];
        if ((entry != null ? entry.draft_id : void 0) != null) {
          existingByDraftId[entry.draft_id] = entry;
        }
      }
      decisions = messageDrafts.drafts.map(function(draft, index) {
        var defaultEntry, draftId, existingEntry, merged, ref10, ref5, ref6, ref7, ref8, ref9, sameCampaign;
        draftId = (ref5 = draft.draft_id) != null ? ref5 : `draft_${index + 1}`;
        defaultEntry = freshDecision(draft, draftId);
        existingEntry = existingByDraftId[draftId];
        sameCampaign = String((ref6 = existingEntry != null ? existingEntry.campaign_source_hash : void 0) != null ? ref6 : '') === currentSourceHash && currentSourceHash.length > 0;
        merged = sameCampaign ? Object.assign({}, defaultEntry, existingEntry) : defaultEntry;
        merged.draft_id = draftId;
        merged.campaign_source_hash = currentSourceHash || null;
        merged.contact_name = (ref7 = (ref8 = draft.contact_name) != null ? ref8 : merged.contact_name) != null ? ref7 : '';
        merged.organization = (ref9 = (ref10 = draft.organization) != null ? ref10 : merged.organization) != null ? ref9 : '';
        if (!(sameCampaign && ((existingEntry != null ? existingEntry.updated_at : void 0) != null))) {
          merged.updated_at = defaultEntry.updated_at;
        }
        return merged;
      });
      for (j = 0, len1 = existingDecisions.length; j < len1; j++) {
        entry = existingDecisions[j];
        if (!(((entry != null ? entry.draft_id : void 0) != null) && !decisions.some(function(row) {
          return row.draft_id === entry.draft_id;
        }))) {
          continue;
        }
        if (!(String((ref5 = entry != null ? entry.campaign_source_hash : void 0) != null ? ref5 : '') === currentSourceHash && currentSourceHash.length > 0)) {
          continue;
        }
        decisions.push(entry);
      }
      payload = {
        generated_for: (ref6 = messageDrafts.generated_for) != null ? ref6 : (ref7 = experiment.run) != null ? ref7.campaign_name : void 0,
        campaign_source_hash: currentSourceHash || null,
        decision_count: decisions.length,
        decisions: decisions,
        notes: {
          draft_only: true,
          no_live_actions: true
        }
      };
      L.make('review_decisions', payload);
      L.done();
    }
  };

}).call(this);
