// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var DEFAULT_SOURCE_TEXT, crypto, deriveBrandName, deriveCampaignName, deriveLaunchCity, splitSentences;

  crypto = require('crypto');

  DEFAULT_SOURCE_TEXT = "Describe this campaign here.\n";

  splitSentences = function(text) {
    if (text == null) {
      return [];
    }
    return text.replace(/\s+/g, ' ').split(/(?<=[.!?])\s+/).map(function(part) {
      return part.trim();
    }).filter(Boolean);
  };

  deriveCampaignName = function(text) {
    var first, lines;
    lines = String(text != null ? text : '').split(/\r?\n/).map(function(line) {
      return line.trim();
    }).filter(Boolean);
    if (!lines.length) {
      return 'Untitled campaign';
    }
    first = lines[0].replace(/^campaign:\s*/i, '').trim();
    first = first.replace(/^brand:\s*/i, '').trim();
    if (first.length) {
      return first.slice(0, 120);
    }
    return 'Untitled campaign';
  };

  deriveBrandName = function(text, campaignName) {
    var brand, brandLine, lines;
    lines = String(text != null ? text : '').split(/\r?\n/).map(function(line) {
      return line.trim();
    }).filter(Boolean);
    brandLine = lines.find(function(line) {
      return /^brand:\s*/i.test(line);
    });
    if (brandLine != null) {
      brand = brandLine.replace(/^brand:\s*/i, '').trim();
      if (brand.length) {
        return brand;
      }
    }
    return String(campaignName != null ? campaignName : 'Campaign').split(/[:,-]/)[0].trim() || 'Campaign';
  };

  deriveLaunchCity = function(text) {
    var cityLine, lines;
    lines = String(text != null ? text : '').split(/\r?\n/).map(function(line) {
      return line.trim();
    }).filter(Boolean);
    cityLine = lines.find(function(line) {
      return /^city:\s*/i.test(line) || /^launch city:\s*/i.test(line);
    });
    if (cityLine == null) {
      return null;
    }
    return cityLine.replace(/^(city|launch city):\s*/i, '').trim() || null;
  };

  this.step = {
    desc: 'Load source material for draft-only publicist planning.',
    action: function(L, stepName, M) {
      var announcementDate, brandName, campaignName, experiment, highlights, launchCity, material, ref, ref1, ref10, ref11, ref12, ref13, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, reviewGoal, sentences, sourceFile, sourceHash, sourceText;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      sourceFile = M.getStepParam(stepName, 'source_file');
      if (sourceFile == null) {
        throw new Error(`[${stepName}] Missing required key 'source_file'`);
      }
      sourceText = (ref1 = M.theLowdown(sourceFile)) != null ? ref1.value : void 0;
      if (sourceText === void 0) {
        M.saveThis(sourceFile, DEFAULT_SOURCE_TEXT);
        sourceText = (ref2 = M.theLowdown(sourceFile)) != null ? ref2.value : void 0;
      }
      if (sourceText == null) {
        throw new Error(`[${stepName}] Missing source material. Attempted key: ${sourceFile}`);
      }
      sourceHash = crypto.createHash('sha256').update(String(sourceText)).digest('hex');
      campaignName = (ref3 = (ref4 = M.getStepParam(stepName, 'campaign_name')) != null ? ref4 : (ref5 = experiment.run) != null ? ref5.campaign_name : void 0) != null ? ref3 : deriveCampaignName(sourceText);
      brandName = (ref6 = (ref7 = M.getStepParam(stepName, 'brand_name')) != null ? ref7 : (ref8 = experiment.run) != null ? ref8.brand_name : void 0) != null ? ref6 : deriveBrandName(sourceText, campaignName);
      launchCity = (ref9 = (ref10 = M.getStepParam(stepName, 'launch_city')) != null ? ref10 : (ref11 = experiment.run) != null ? ref11.launch_city : void 0) != null ? ref9 : deriveLaunchCity(sourceText);
      announcementDate = M.getStepParam(stepName, 'announcement_date');
      reviewGoal = (ref12 = M.getStepParam(stepName, 'review_goal')) != null ? ref12 : 'Prepare reviewed outreach drafts only.';
      sentences = splitSentences(sourceText);
      highlights = sentences.slice(0, 4);
      material = {
        campaign_name: campaignName,
        brand_name: brandName,
        launch_city: launchCity,
        announcement_date: announcementDate,
        review_goal: reviewGoal,
        source_hash: sourceHash,
        source_file: sourceFile,
        source_text: sourceText.trim(),
        highlights: highlights,
        notes: {
          experiment_output_dir: (ref13 = experiment.run) != null ? ref13.output_dir : void 0,
          draft_only: true,
          no_live_actions: true
        }
      };
      L.make('source_material', material);
      L.done();
    }
  };

}).call(this);
