// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var isBlank, makeSearchTerms, slugify;

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  slugify = function(value) {
    return String(value != null ? value : '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  };

  makeSearchTerms = function(...parts) {
    var i, len, part, seen, terms, text;
    terms = [];
    seen = new Set();
    for (i = 0, len = parts.length; i < len; i++) {
      part = parts[i];
      if (!(!isBlank(part))) {
        continue;
      }
      text = String(part).trim();
      if (seen.has(text)) {
        continue;
      }
      seen.add(text);
      terms.push(text);
    }
    return terms;
  };

  this.step = {
    desc: 'Plan publicist research requests without performing web access.',
    action: async function(L, stepName, M) {
      var audience, audienceId, audienceName, audienceProfiles, audienceProfilesKey, contactLedger, contactLedgerKey, currentSourceHash, entry, existingByRequestId, existingDoc, existingRequests, experiment, hasExplicitNextActions, i, identity, j, k, l, ledgerByAudience, ledgerByIdentity, ledgerEntry, len, len1, len2, len3, len4, len5, len6, len7, len8, m, n, newCount, nextActions, nextActionsKey, o, p, payload, preservedCount, profile, profileByLabel, pushRequest, q, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref19, ref2, ref20, ref21, ref22, ref23, ref24, ref25, ref26, ref27, ref28, ref29, ref3, ref30, ref31, ref32, ref33, ref34, ref35, ref36, ref37, ref38, ref39, ref4, ref40, ref41, ref42, ref43, ref44, ref45, ref46, ref47, ref48, ref49, ref5, ref50, ref51, ref52, ref53, ref54, ref55, ref56, ref57, ref58, ref6, ref7, ref8, ref9, request, requests, researchRequestsTarget, row, seenRequestIds;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      contactLedgerKey = 'contact_ledger';
      audienceProfilesKey = 'audience_profiles';
      nextActionsKey = 'next_actions';
      contactLedger = (await L.need(contactLedgerKey));
      audienceProfiles = (await L.need(audienceProfilesKey));
      nextActions = (await L.need(nextActionsKey));
      if ((contactLedger != null ? contactLedger.entries : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${contactLedgerKey}'`);
      }
      if ((audienceProfiles != null ? audienceProfiles.profiles : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${audienceProfilesKey}'`);
      }
      if (nextActions == null) {
        throw new Error(`[${stepName}] Missing required artifact '${nextActionsKey}'`);
      }
      currentSourceHash = String((ref1 = (ref2 = (ref3 = nextActions != null ? nextActions.campaign_source_hash : void 0) != null ? ref3 : contactLedger != null ? contactLedger.campaign_source_hash : void 0) != null ? ref2 : audienceProfiles != null ? audienceProfiles.campaign_source_hash : void 0) != null ? ref1 : '');
      researchRequestsTarget = (ref4 = experiment.artifacts) != null ? (ref5 = ref4.research_requests) != null ? ref5.target : void 0 : void 0;
      existingDoc = researchRequestsTarget != null ? (ref6 = M.theLowdown(researchRequestsTarget)) != null ? ref6.value : void 0 : null;
      existingRequests = Array.isArray(existingDoc != null ? existingDoc.research_requests : void 0) ? existingDoc.research_requests : [];
      existingByRequestId = {};
      for (i = 0, len = existingRequests.length; i < len; i++) {
        entry = existingRequests[i];
        if ((entry != null ? entry.request_id : void 0) != null) {
          existingByRequestId[entry.request_id] = entry;
        }
      }
      ledgerByAudience = {};
      ledgerByIdentity = {};
      ref7 = contactLedger.entries;
      for (j = 0, len1 = ref7.length; j < len1; j++) {
        entry = ref7[j];
        if ((entry != null ? entry.audience : void 0) != null) {
          ledgerByAudience[entry.audience] = entry;
        }
        identity = `${(ref8 = entry.organization) != null ? ref8 : ''}::${(ref9 = entry.contact_name) != null ? ref9 : ''}`;
        ledgerByIdentity[identity] = entry;
      }
      profileByLabel = {};
      ref10 = audienceProfiles.profiles;
      for (k = 0, len2 = ref10.length; k < len2; k++) {
        profile = ref10[k];
        if ((profile != null ? profile.audience_label : void 0) != null) {
          profileByLabel[profile.audience_label] = profile;
        }
      }
      requests = [];
      seenRequestIds = new Set();
      preservedCount = 0;
      newCount = 0;
      pushRequest = function(payload) {
        var existingEntry, field, l, len3, merged, ref11, ref12, requestId, sameCampaign;
        requestId = payload.request_id;
        if (!((requestId != null) && requestId.length)) {
          return;
        }
        if (seenRequestIds.has(requestId)) {
          return;
        }
        seenRequestIds.add(requestId);
        existingEntry = existingByRequestId[requestId];
        sameCampaign = String((ref11 = existingEntry != null ? existingEntry.campaign_source_hash : void 0) != null ? ref11 : '') === currentSourceHash && currentSourceHash.length > 0;
        if (sameCampaign) {
          merged = Object.assign({}, payload);
          if (Array.isArray(existingEntry.suggested_search_terms)) {
            merged.suggested_search_terms = existingEntry.suggested_search_terms;
          }
          ref12 = ['status', 'allowed_domains', 'reviewer_notes', 'reviewed_at', 'review_required'];
          for (l = 0, len3 = ref12.length; l < len3; l++) {
            field = ref12[l];
            if (existingEntry[field] != null) {
              merged[field] = existingEntry[field];
            }
          }
          requests.push(merged);
          return preservedCount += 1;
        } else {
          requests.push(payload);
          return newCount += 1;
        }
      };
      ref12 = (ref11 = nextActions.follow_up_contacts) != null ? ref11 : [];
      for (l = 0, len3 = ref12.length; l < len3; l++) {
        row = ref12[l];
        identity = `${(ref13 = row.organization) != null ? ref13 : ''}::${(ref14 = row.contact_name) != null ? ref14 : ''}`;
        ledgerEntry = ledgerByIdentity[identity];
        audience = (ref15 = (ref16 = row.audience_label) != null ? ref16 : ledgerEntry != null ? ledgerEntry.audience : void 0) != null ? ref15 : '';
        pushRequest({
          request_id: `research_follow_up_${slugify((ref17 = (ref18 = row.draft_id) != null ? ref18 : identity) != null ? ref17 : audience)}`,
          audience: audience,
          organization: (ref19 = (ref20 = row.organization) != null ? ref20 : ledgerEntry != null ? ledgerEntry.organization : void 0) != null ? ref19 : '',
          contact_name: (ref21 = (ref22 = row.contact_name) != null ? ref22 : ledgerEntry != null ? ledgerEntry.contact_name : void 0) != null ? ref21 : '',
          research_goal: 'Gather context that would improve a reviewed follow-up plan for an already approved target.',
          suggested_search_terms: makeSearchTerms(row.organization, row.contact_name, audience, (ref23 = experiment.run) != null ? ref23.campaign_name : void 0, (ref24 = experiment.run) != null ? ref24.launch_city : void 0),
          allowed_domains: [],
          status: 'planned_only',
          review_required: true
        });
      }
      ref26 = (ref25 = nextActions.audiences_to_expand) != null ? ref25 : [];
      for (m = 0, len4 = ref26.length; m < len4; m++) {
        row = ref26[m];
        profile = profileByLabel[row.audience_label];
        ledgerEntry = ledgerByAudience[row.audience_label];
        pushRequest({
          request_id: `research_expand_${slugify((ref27 = row.audience_key) != null ? ref27 : row.audience_label)}`,
          audience: (ref28 = row.audience_label) != null ? ref28 : '',
          organization: (ref29 = ledgerEntry != null ? ledgerEntry.organization : void 0) != null ? ref29 : '',
          contact_name: (ref30 = ledgerEntry != null ? ledgerEntry.contact_name : void 0) != null ? ref30 : '',
          research_goal: 'Find better-fit outlets, editors, or context to expand coverage for an audience with zero approved drafts.',
          suggested_search_terms: makeSearchTerms(row.audience_label, profile != null ? profile.angle : void 0, profile != null ? profile.rationale : void 0, (ref31 = experiment.run) != null ? ref31.campaign_name : void 0, (ref32 = experiment.run) != null ? ref32.launch_city : void 0),
          allowed_domains: [],
          status: 'planned_only',
          review_required: true
        });
      }
      ref34 = (ref33 = nextActions.drafts_needing_review) != null ? ref33 : [];
      for (n = 0, len5 = ref34.length; n < len5; n++) {
        row = ref34[n];
        identity = `${(ref35 = row.organization) != null ? ref35 : ''}::${(ref36 = row.contact_name) != null ? ref36 : ''}`;
        ledgerEntry = ledgerByIdentity[identity];
        audience = (ref37 = ledgerEntry != null ? ledgerEntry.audience : void 0) != null ? ref37 : '';
        profile = profileByLabel[audience];
        pushRequest({
          request_id: `research_review_${slugify((ref38 = (ref39 = row.draft_id) != null ? ref39 : identity) != null ? ref38 : audience)}`,
          audience: audience,
          organization: (ref40 = (ref41 = row.organization) != null ? ref41 : ledgerEntry != null ? ledgerEntry.organization : void 0) != null ? ref40 : '',
          contact_name: (ref42 = (ref43 = row.contact_name) != null ? ref43 : ledgerEntry != null ? ledgerEntry.contact_name : void 0) != null ? ref42 : '',
          research_goal: 'Collect background context that would help a human reviewer strengthen or reframe a pending draft.',
          suggested_search_terms: makeSearchTerms(row.organization, row.contact_name, audience, profile != null ? profile.angle : void 0, (ref44 = experiment.run) != null ? ref44.campaign_name : void 0),
          allowed_domains: [],
          status: 'planned_only',
          review_required: true
        });
      }
      hasExplicitNextActions = ((ref45 = nextActions.follow_up_contacts) != null ? ref45 : []).length > 0 || ((ref46 = nextActions.audiences_to_expand) != null ? ref46 : []).length > 0 || ((ref47 = nextActions.drafts_needing_review) != null ? ref47 : []).length > 0;
      if (!hasExplicitNextActions) {
        ref48 = audienceProfiles.profiles;
        for (o = 0, len6 = ref48.length; o < len6; o++) {
          profile = ref48[o];
          audienceId = (ref49 = (ref50 = profile.audience_key) != null ? ref50 : profile.audience_label) != null ? ref49 : 'audience';
          audienceName = (ref51 = (ref52 = profile.audience_label) != null ? ref52 : profile.audience_key) != null ? ref51 : '';
          pushRequest({
            request_id: `research_${slugify(audienceId)}_background`,
            audience: audienceName,
            organization: "",
            contact_name: "",
            research_goal: 'General background and positioning research for this audience.',
            suggested_search_terms: [`${audienceName} publications`, `${audienceName} outreach opportunities`, `${audienceName} relevant organizations`],
            allowed_domains: [],
            status: 'planned_only',
            review_required: true
          });
        }
      }
      for (p = 0, len7 = existingRequests.length; p < len7; p++) {
        entry = existingRequests[p];
        if (!(((entry != null ? entry.request_id : void 0) != null) && !seenRequestIds.has(entry.request_id))) {
          continue;
        }
        if (!(String((ref53 = entry != null ? entry.campaign_source_hash : void 0) != null ? ref53 : '') === currentSourceHash && currentSourceHash.length > 0)) {
          continue;
        }
        seenRequestIds.add(entry.request_id);
        requests.push(entry);
      }
      for (q = 0, len8 = requests.length; q < len8; q++) {
        request = requests[q];
        request.campaign_source_hash = currentSourceHash || null;
      }
      payload = {
        generated_for: (ref54 = nextActions.generated_for) != null ? ref54 : (ref55 = experiment.run) != null ? ref55.campaign_name : void 0,
        campaign_source_hash: currentSourceHash || null,
        request_count: requests.length,
        preserved_count: preservedCount,
        new_count: newCount,
        approved_count: requests.filter(function(row) {
          var ref56;
          return String((ref56 = row != null ? row.status : void 0) != null ? ref56 : '').trim().toLowerCase() === 'approved_for_research';
        }).length,
        research_requests: requests,
        summary: {
          planned_only: true,
          follow_up_contacts_source_count: ((ref56 = nextActions.follow_up_contacts) != null ? ref56 : []).length,
          audiences_to_expand_source_count: ((ref57 = nextActions.audiences_to_expand) != null ? ref57 : []).length,
          drafts_needing_review_source_count: ((ref58 = nextActions.drafts_needing_review) != null ? ref58 : []).length,
          used_fallback_planner: !hasExplicitNextActions
        }
      };
      L.make('research_requests', payload);
      L.done();
    }
  };

}).call(this);
