// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var daysBetween, isBlank;

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  daysBetween = function(olderIso, newerDate = new Date()) {
    var older;
    older = new Date(olderIso);
    if (Number.isNaN(older.getTime())) {
      return null;
    }
    return Math.floor((newerDate.getTime() - older.getTime()) / (24 * 60 * 60 * 1000));
  };

  this.step = {
    desc: 'Suggest next publicist actions from SQLite insights and current artifacts.',
    action: async function(L, stepName, M) {
      var ageDays, audiencesToExpand, contactLedger, contactLedgerKey, decision, draftsNeedingReview, experiment, followUpContacts, i, len, now, payload, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, reviewDecisions, reviewDecisionsKey, sqliteInsights, sqliteInsightsKey, staleAfterDays, staleItems;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      sqliteInsightsKey = 'sqlite_insights';
      contactLedgerKey = 'contact_ledger';
      reviewDecisionsKey = 'review_decisions';
      sqliteInsights = (await L.need(sqliteInsightsKey));
      contactLedger = (await L.need(contactLedgerKey));
      reviewDecisions = (await L.need(reviewDecisionsKey));
      if (sqliteInsights == null) {
        throw new Error(`[${stepName}] Missing required artifact '${sqliteInsightsKey}'`);
      }
      if ((contactLedger != null ? contactLedger.entries : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${contactLedgerKey}'`);
      }
      if ((reviewDecisions != null ? reviewDecisions.decisions : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${reviewDecisionsKey}'`);
      }
      staleAfterDays = Number((ref1 = M.getStepParam(stepName, 'stale_after_days')) != null ? ref1 : 14);
      now = new Date();
      followUpContacts = ((ref2 = sqliteInsights.pending_outreach) != null ? ref2 : []).map(function(row) {
        var ref3, ref4, ref5, ref6;
        return {
          draft_id: row.draft_id,
          audience_label: (ref3 = row.audience_label) != null ? ref3 : '',
          organization: (ref4 = row.organization) != null ? ref4 : '',
          contact_name: (ref5 = row.contact_name) != null ? ref5 : '',
          reviewed_at: (ref6 = row.reviewed_at) != null ? ref6 : null,
          recommendation: 'Prepare reviewed follow-up plan only; no send action in this phase.'
        };
      });
      audiencesToExpand = ((ref3 = sqliteInsights.empty_audiences) != null ? ref3 : []).map(function(row) {
        var ref4, ref5;
        return {
          audience_key: (ref4 = row.audience_key) != null ? ref4 : '',
          audience_label: (ref5 = row.audience_label) != null ? ref5 : '',
          recommendation: 'Add or improve approved draft coverage for this audience.'
        };
      });
      draftsNeedingReview = reviewDecisions.decisions.filter(function(decision) {
        var ref4;
        return String((ref4 = decision != null ? decision.decision : void 0) != null ? ref4 : '').trim().toLowerCase() === 'pending_review';
      }).map(function(decision) {
        var ref4, ref5, ref6;
        return {
          draft_id: (ref4 = decision.draft_id) != null ? ref4 : '',
          contact_name: (ref5 = decision.contact_name) != null ? ref5 : '',
          organization: (ref6 = decision.organization) != null ? ref6 : '',
          recommendation: 'Human review still pending.'
        };
      });
      staleItems = [];
      ref4 = reviewDecisions.decisions;
      for (i = 0, len = ref4.length; i < len; i++) {
        decision = ref4[i];
        if (!(!isBlank(decision != null ? decision.reviewed_at : void 0))) {
          continue;
        }
        ageDays = daysBetween(decision.reviewed_at, now);
        if (!((ageDays != null) && ageDays >= staleAfterDays)) {
          continue;
        }
        staleItems.push({
          draft_id: (ref5 = decision.draft_id) != null ? ref5 : '',
          contact_name: (ref6 = decision.contact_name) != null ? ref6 : '',
          organization: (ref7 = decision.organization) != null ? ref7 : '',
          decision: (ref8 = decision.decision) != null ? ref8 : '',
          reviewed_at: decision.reviewed_at,
          age_days: ageDays,
          recommendation: 'Recheck whether this reviewed item still reflects current priorities.'
        });
      }
      payload = {
        generated_for: (ref9 = experiment.run) != null ? ref9.campaign_name : void 0,
        follow_up_contacts: followUpContacts,
        audiences_to_expand: audiencesToExpand,
        drafts_needing_review: draftsNeedingReview,
        stale_items: staleItems,
        summary: {
          db_available: ((ref10 = sqliteInsights.summary) != null ? ref10.db_available : void 0) === true,
          follow_up_contacts_count: followUpContacts.length,
          audiences_to_expand_count: audiencesToExpand.length,
          drafts_needing_review_count: draftsNeedingReview.length,
          stale_items_count: staleItems.length,
          stale_after_days: staleAfterDays
        }
      };
      L.make('next_actions', payload);
      L.done();
    }
  };

}).call(this);
