// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var DatabaseSync, boolToInt, findLedgerEntryForDraft, fs, isBlank, isFullyApprovedDecision, path;

  fs = require('fs');

  path = require('path');

  ({DatabaseSync} = require('node:sqlite'));

  isBlank = function(value) {
    return String(value != null ? value : '').trim().length === 0;
  };

  boolToInt = function(value) {
    if (value === true) {
      return 1;
    } else {
      return 0;
    }
  };

  isFullyApprovedDecision = function(decision) {
    var ref;
    return (decision != null ? decision.approved_for_send : void 0) === true && String((ref = decision != null ? decision.decision : void 0) != null ? ref : '').trim().toLowerCase() === 'approved' && !isBlank(decision != null ? decision.reviewed_at : void 0);
  };

  findLedgerEntryForDraft = function(contactLedger, draft) {
    if (!Array.isArray(contactLedger != null ? contactLedger.entries : void 0)) {
      return null;
    }
    return contactLedger.entries.find(function(entry) {
      var ref, ref1, ref2, ref3;
      return String((ref = entry != null ? entry.organization : void 0) != null ? ref : '') === String((ref1 = draft != null ? draft.organization : void 0) != null ? ref1 : '') && String((ref2 = entry != null ? entry.contact_name : void 0) != null ? ref2 : '') === String((ref3 = draft != null ? draft.contact_name : void 0) != null ? ref3 : '');
    });
  };

  this.step = {
    desc: 'Write approved publicist contact/draft/review metadata into SQLite.',
    action: async function(L, stepName, M) {
      var approvedDecisions, contactLedger, contactLedgerKey, db, dbWritePerformed, decision, draft, draftById, err, experiment, findAudienceByKeyStmt, findAudienceByLabelStmt, findContactStmt, findDraftStmt, findReviewDecisionStmt, i, insertContactStmt, insertDraftStmt, insertReviewDecisionStmt, j, len, len1, messageDrafts, messageDraftsKey, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, report, reviewDecisions, reviewDecisionsKey, sqlitePath, tx, updateContactStmt, updateDraftStmt, updateReviewDecisionStmt;
      experiment = (ref = M.theLowdown('experiment.yaml')) != null ? ref.value : void 0;
      if (experiment == null) {
        throw new Error(`[${stepName}] Missing experiment.yaml in Memo`);
      }
      contactLedgerKey = 'contact_ledger';
      messageDraftsKey = 'message_drafts';
      reviewDecisionsKey = 'review_decisions';
      contactLedger = (await L.need(contactLedgerKey));
      messageDrafts = (await L.need(messageDraftsKey));
      reviewDecisions = (await L.need(reviewDecisionsKey));
      if ((contactLedger != null ? contactLedger.entries : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${contactLedgerKey}'`);
      }
      if ((messageDrafts != null ? messageDrafts.drafts : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${messageDraftsKey}'`);
      }
      if ((reviewDecisions != null ? reviewDecisions.decisions : void 0) == null) {
        throw new Error(`[${stepName}] Missing required artifact '${reviewDecisionsKey}'`);
      }
      sqlitePath = path.resolve(String((ref1 = (ref2 = M.getStepParam(stepName, 'sqlite_db')) != null ? ref2 : (ref3 = experiment.run) != null ? ref3['runtime.sqlite'] : void 0) != null ? ref1 : 'runtime/publicist.sqlite'));
      report = {
        generated_for: (ref4 = experiment.run) != null ? ref4.campaign_name : void 0,
        sqlite_path: sqlitePath,
        approval_filter: 'approved_for_send = true',
        rows_written: {
          contacts: 0,
          drafts: 0,
          review_decisions: 0
        },
        skipped: {
          not_fully_approved: 0
        },
        errors: []
      };
      if (!fs.existsSync(sqlitePath)) {
        report.errors.push({
          type: 'missing_sqlite_db',
          detail: `SQLite DB missing at ${sqlitePath}`
        });
        report.summary = {
          approved_count: 0,
          skipped_not_fully_approved: report.skipped.not_fully_approved,
          error_count: report.errors.length,
          db_write_performed: false
        };
        L.make('sqlite_write_report', report);
        L.done();
        return;
      }
      draftById = {};
      ref5 = messageDrafts.drafts;
      for (i = 0, len = ref5.length; i < len; i++) {
        draft = ref5[i];
        if ((draft != null ? draft.draft_id : void 0) != null) {
          draftById[draft.draft_id] = draft;
        }
      }
      approvedDecisions = [];
      ref6 = reviewDecisions.decisions;
      for (j = 0, len1 = ref6.length; j < len1; j++) {
        decision = ref6[j];
        if (isFullyApprovedDecision(decision)) {
          approvedDecisions.push(decision);
        } else {
          report.skipped.not_fully_approved += 1;
        }
      }
      db = new DatabaseSync(sqlitePath);
      dbWritePerformed = false;
      try {
        findAudienceByKeyStmt = db.prepare('SELECT id, audience_key, audience_label FROM audiences WHERE audience_key = ? LIMIT 1');
        findAudienceByLabelStmt = db.prepare('SELECT id, audience_key, audience_label FROM audiences WHERE audience_label = ? LIMIT 1');
        findContactStmt = db.prepare('SELECT id FROM contacts WHERE audience_id = ? AND organization = ? AND ifnull(contact_name, "") = ifnull(?, "") LIMIT 1');
        insertContactStmt = db.prepare(`INSERT INTO contacts (
  audience_id, organization, contact_name, contact_role, contact_channel,
  status, rationale, next_action, review_required, source_artifact_key,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
        updateContactStmt = db.prepare(`UPDATE contacts
SET contact_role = ?, contact_channel = ?, status = ?, rationale = ?, next_action = ?,
    review_required = ?, source_artifact_key = ?, updated_at = ?
WHERE id = ?`);
        findDraftStmt = db.prepare('SELECT id FROM drafts WHERE draft_id = ? LIMIT 1');
        insertDraftStmt = db.prepare(`INSERT INTO drafts (
  draft_id, audience_id, contact_id, subject, pitch_summary, artifact_key,
  artifact_path, review_required, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
        updateDraftStmt = db.prepare(`UPDATE drafts
SET audience_id = ?, contact_id = ?, subject = ?, pitch_summary = ?, artifact_key = ?,
    artifact_path = ?, review_required = ?, status = ?, updated_at = ?
WHERE id = ?`);
        findReviewDecisionStmt = db.prepare('SELECT id FROM review_decisions WHERE draft_id = ? LIMIT 1');
        insertReviewDecisionStmt = db.prepare(`INSERT INTO review_decisions (
  draft_id, decision, reviewer_notes, approved_for_send, reviewed_at,
  artifact_key, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`);
        updateReviewDecisionStmt = db.prepare(`UPDATE review_decisions
SET decision = ?, reviewer_notes = ?, approved_for_send = ?, reviewed_at = ?,
    artifact_key = ?, updated_at = ?
WHERE id = ?`);
        tx = db.transaction(function(rows) {
          var audienceRow, contactID, contactResult, contactRow, draftId, draftRow, k, ledgerEntry, len2, now, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref19, ref20, ref21, ref22, ref23, ref24, ref25, ref26, ref27, ref28, ref29, ref30, ref31, ref32, ref33, ref34, ref35, ref7, ref8, ref9, results, reviewDecisionRow;
          results = [];
          for (k = 0, len2 = rows.length; k < len2; k++) {
            decision = rows[k];
            draftId = String((ref7 = decision != null ? decision.draft_id : void 0) != null ? ref7 : '').trim();
            draft = draftById[draftId];
            if (draft == null) {
              report.errors.push({
                type: 'missing_draft',
                draft_id: draftId,
                detail: `No message_drafts row for approved draft_id '${draftId}'`
              });
              continue;
            }
            ledgerEntry = findLedgerEntryForDraft(contactLedger, draft);
            if (ledgerEntry == null) {
              report.errors.push({
                type: 'missing_contact_ledger_entry',
                draft_id: draftId,
                detail: `No contact_ledger row for '${(ref8 = draft.organization) != null ? ref8 : ''}::${(ref9 = draft.contact_name) != null ? ref9 : ''}'`
              });
              continue;
            }
            audienceRow = null;
            if (!isBlank(draft.audience_key)) {
              audienceRow = findAudienceByKeyStmt.get(draft.audience_key);
            }
            if ((audienceRow == null) && !isBlank(draft.audience_label)) {
              audienceRow = findAudienceByLabelStmt.get(draft.audience_label);
            }
            if ((audienceRow == null) && !isBlank(ledgerEntry.audience)) {
              audienceRow = findAudienceByLabelStmt.get(ledgerEntry.audience);
            }
            if (audienceRow == null) {
              report.errors.push({
                type: 'missing_audience_row',
                draft_id: draftId,
                detail: `No audiences row found for approved draft '${draftId}'`
              });
              continue;
            }
            now = new Date().toISOString();
            contactRow = findContactStmt.get(audienceRow.id, ledgerEntry.organization, (ref10 = ledgerEntry.contact_name) != null ? ref10 : null);
            if (contactRow != null) {
              updateContactStmt.run((ref11 = ledgerEntry.contact_role) != null ? ref11 : null, (ref12 = ledgerEntry.contact_channel) != null ? ref12 : null, 'approved_for_send', (ref13 = ledgerEntry.rationale) != null ? ref13 : null, (ref14 = ledgerEntry.next_action) != null ? ref14 : null, boolToInt(ledgerEntry.review_required), 'contact_ledger', now, contactRow.id);
              contactID = contactRow.id;
              report.rows_written.contacts += 1;
            } else {
              contactResult = insertContactStmt.run(audienceRow.id, ledgerEntry.organization, (ref15 = ledgerEntry.contact_name) != null ? ref15 : null, (ref16 = ledgerEntry.contact_role) != null ? ref16 : null, (ref17 = ledgerEntry.contact_channel) != null ? ref17 : null, 'approved_for_send', (ref18 = ledgerEntry.rationale) != null ? ref18 : null, (ref19 = ledgerEntry.next_action) != null ? ref19 : null, boolToInt(ledgerEntry.review_required), 'contact_ledger', now, now);
              contactID = contactResult.lastInsertRowid;
              report.rows_written.contacts += 1;
            }
            draftRow = findDraftStmt.get(draftId);
            if (draftRow != null) {
              updateDraftStmt.run(audienceRow.id, contactID, (ref20 = draft.subject) != null ? ref20 : null, (ref21 = draft.pitch_summary) != null ? ref21 : null, 'message_drafts', (ref22 = (ref23 = experiment.artifacts) != null ? (ref24 = ref23.message_drafts) != null ? ref24.target : void 0 : void 0) != null ? ref22 : null, boolToInt(draft.review_required), 'approved_for_send', now, draftRow.id);
              report.rows_written.drafts += 1;
            } else {
              insertDraftStmt.run(draftId, audienceRow.id, contactID, (ref25 = draft.subject) != null ? ref25 : null, (ref26 = draft.pitch_summary) != null ? ref26 : null, 'message_drafts', (ref27 = (ref28 = experiment.artifacts) != null ? (ref29 = ref28.message_drafts) != null ? ref29.target : void 0 : void 0) != null ? ref27 : null, boolToInt(draft.review_required), 'approved_for_send', now, now);
              report.rows_written.drafts += 1;
            }
            reviewDecisionRow = findReviewDecisionStmt.get(draftId);
            if (reviewDecisionRow != null) {
              updateReviewDecisionStmt.run((ref30 = decision.decision) != null ? ref30 : 'approved', (ref31 = decision.reviewer_notes) != null ? ref31 : '', boolToInt(decision.approved_for_send), (ref32 = decision.reviewed_at) != null ? ref32 : null, 'review_decisions', now, reviewDecisionRow.id);
              results.push(report.rows_written.review_decisions += 1);
            } else {
              insertReviewDecisionStmt.run(draftId, (ref33 = decision.decision) != null ? ref33 : 'approved', (ref34 = decision.reviewer_notes) != null ? ref34 : '', boolToInt(decision.approved_for_send), (ref35 = decision.reviewed_at) != null ? ref35 : null, 'review_decisions', now, now);
              results.push(report.rows_written.review_decisions += 1);
            }
          }
          return results;
        });
        tx(approvedDecisions);
        dbWritePerformed = true;
      } catch (error) {
        err = error;
        report.errors.push({
          type: 'sqlite_write_failed',
          detail: String((ref7 = err != null ? err.message : void 0) != null ? ref7 : err)
        });
      } finally {
        db.close();
      }
      report.summary = {
        approved_count: approvedDecisions.length,
        skipped_not_fully_approved: report.skipped.not_fully_approved,
        error_count: report.errors.length,
        db_write_performed: dbWritePerformed
      };
      L.make('sqlite_write_report', report);
      L.done();
    }
  };

}).call(this);
